### ISSUE TITLE
Switch of logs when Qso list open fails

### ISSUE THREAD

**Issue by OH1KH** [ok2cqr/cqrlog#163]
Log change does not work from "New qso/Open or create new database" when qso list is open
Open cqrlog, open qso list.
Switch log New qso/Open or create new database to another.
Qso list stays empty.
Press refresh button at qso list.
Error: qCqrlog: Field not found: " id_cqrlog_main"

**Comment by dl7oap** [comment]
a first short look:

the error happens in fMain.pas in Column 860

procedure TfrmMain.acRefreshExecute(Sender: TObject);
var
  idx: integer;
begin
  if InRefresh then
    exit;
  try
    InRefresh := True;
    //if user push refresh data very quickly again and again, program
may crash
    idx := dmData.qCQRLOG.FieldByName('id_cqrlog_main').AsInteger;
    dmData.qCQRLOG.Close;
    dmData.RefreshMainDatabase(idx);
    RefreshQSODXCCCount
  finally
    InRefresh := False
  end
end;    

there is in dmData.qCQRLOG the following SQL Statement:
"select * from view_cqrlog_main_by_qsodate LIMIT 500 OFFSET 0"

so it seems, that, due to the change of the schema of the database
dmData can not follow to the other schema and the view there.

the view "view_cqrlog_main_by_qsodate" itself is correct and the field
id_cqrlog_main is there available. the view you can find in dmData
Formular and there in the component scViews.

solution: at the moment i did not know a solution. maybe dmData needs a
kind of refresh or a close and new open of the object. maybe the qso
list form is still initialized with an old dmData object. so maybe the
old dmData Object have to be destroyed and a new fresh instance have to
be created ?
