### ISSUE TITLE
Profile / my Locator is not considered upon ADIF import

### ISSUE THREAD

**Issue by phl0** [ok2cqr/cqrlog#373]
I just imported several QSO logged with another contest log program. Upon import I selected a profile with a locator which differs from my home QTH. The imported QSOs now have the last locator I set with "CTRL + L" when I logged from a different grid. It seems the locator of the selected profile is ignored when importing ADIF files.

**Comment by phl0** [comment]
Some more research: 
If you change your locator (which only was meant to be temporary I think) using CTRL + L this is saved as station locator on exiting the program. But the temporary locator set while logging a QSO is reset after saving the QSO. This looks a bit weird ...

**Comment by phl0** [comment]
Did some patch in order to at least read the grid locator from the selected profile:

https://github.com/phl0/cqrlog/tree/useMyLocFromProfileOnAdifImport

**Comment by OH1KH** [comment]
HI Good point!
If we think situation what should be winner?
1) qth profile locator selected
2) temporary locator set (that is different than qth profile's)
3) locator that is imported with adif

I think the locator imported should roll over all others. That is because log from other program should be set according qth where it was used and qsos recorded.

But that temporary locator is saved as station locator when closing program is wrong. It should disappear when program is closed.
I have not yet checked your patch. These is just my thinking before looking at thencode.

**Comment by phl0** [comment]
I agree. What about a little drop down box to select which of the three should be used?

**Comment by OH1KH** [comment]
IMHO
Locator that is imported (mylog) from adif should always win. It is the other program's, that produces adif export, duty to assign used myloc.

If program does not produce myloc tag to export then import of that kind should use currently set myloc of cqrlog. Station, qth profile or temporary.
(Is it already so that non existing tags take value from cqrlog settings and only imported tags roll over?)

Keeping temporary myloc should be fixed to last for all logged qsos until it is changed (ctrlL), qth profile changed, log changed or cqrlog closed.

That order we do not need selection box. If not included to imported adif, then currently set is valid.

And after all we have GroupEdit to use if needed.

That is what I think. I may be wrong.

**Comment by phl0** [comment]
Sounds like a good idea. Need to create some ADIFs with my_loc set to test.

**Comment by OH1KH** [comment]
OK! Looking forward to hear about it.
It is officially called <MY_GRIDSQUARE: and cqrlog exports it properly (if set)

**Comment by phl0** [comment]
Had a further look at the code and did some tests. It seems that with my commit mentioned above it now works as we agreed:

1. If MY_GRIDSQUARE is provided by the ADIF file that is used to fill my_loc field
2. If MY_GRIDSQUARE is absent the grid from the selected profile is used as my_loc field.
3. If 1 does not apply and the profile does not provide a valid grid the configured station locator from .ini file is used.

So only issue left is to debug where the temporary locator is set and when and where that is stored/used.

**Comment by OH1KH** [comment]
Good!
The temporary needs fix that it keeps valid after saving a qso (manually) because we can assume qsos are held from place that is not station's usual qth, and has no own profile created.
When that works, then that temporary locator works also when import  is done in cases you state.

**Comment by phl0** [comment]
Found the place where the temp. grid loc is saved to config and disabled it for now:
https://github.com/ok2cqr/cqrlog/commit/1d3b436c16645f15bcb8401392cbeb20139bab4a
Still digging in the code to find the reason why the grid loc is reset to default after saving the QSO.

**Comment by phl0** [comment]
@OH1KH Commit https://github.com/phl0/cqrlog/commit/bd0e36b07977c2c41c2f381e5b81d3b04922679e fixes the issue with reset to profile locator.

The initial code was yours from https://github.com/ok2cqr/cqrlog/commit/d05fc4bd1f165812558cc8b9e1b72459ef987eed. I cannot see why this was needed here. Maybe u remeber?

**Comment by OH1KH** [comment]
I'm glad I have written longer explain. Otherwise I could not say anything...
Situation what happens was weird. As said if you have imported qsos with different qth profiles and then view or edit them New qso adopts locator from that qsos profile and keeps it when you manually add next qso. How ever qth profile selector shows empty and then the preference's my loc is assumed to be used. How ever it is locator from last viewed/edited different profile qso.

Perhaps I did not test all the variants after making change.

Edit/view qso should NOT take it's locator to be valid for next new qsos. If no profile is selected myloc should return to station loc from preferences, or keep the previously set CtrlL temporary locator for next new qsos entered.

And as you noticed CtrlL temporary locator should NOT reset by saving a new qso. Only by setting new with CtrlL, change qth profile, change log or close cqrlog should reset it.

I remember it is very complicated issue as there are temporary loc, station loc and qth profile loc , and now also imported myloc to test between. It is very easy to blow you mind with tests.

But think you are closer now than I was then.

**Comment by phl0** [comment]
Could you re-test your case with the ADIF import with my patch set?

**Comment by OH1KH** [comment]
Comments via EMail

**Comment by OH1KH** [comment]
For other followers FYI:

We have found a bug in qth profile number creation that will be fixed.

Still open question is what to do for adif imports that do not have MY_GRIDSQUARE tag.

Should they have: 
 - station locator (from preferences. That happens now), 
 - or a temporary locator (changed by Ctrl-L, if differs from station locator and  is selected at import time) 
 - or qth profile's locator (if qth profile is selected at import time) and it that case should they also have profile number set by qth profile, or just MY_GRIDSQUARE to be set by qth profile's locator.

**Comment by phl0** [comment]
Current status is: If MY_GRIDSQUARE is present it is used as my_loc in database. If the ADIF tag is not present my_loc is either set to the grid taken from the selected profile or the station's locator from config if no or and invalid profile is selected.

I have added some more code with a separate checkbox that allows to override the grid locator upon import even if MY_GRIDSQUARE is present in the file. If that box is checked again either the profile's locator or station's config locator is used as my_loc regardless of what or if MY_GRIDSQUARE is present in the ADIF file.

![Screenshot from 2021-02-05 13-56-02](https://user-images.githubusercontent.com/7112907/107036768-6ae67c00-67ba-11eb-99a2-437709285679.png)

If nobody complains (wink at @OH1KH) I will PR the code from my https://github.com/phl0/cqrlog/tree/useMyLocFromProfileOnAdifImport branch (after editing the documentation of course).

**Comment by OH1KH** [comment]
HI!
No complains  .-)

I think this way user can select "my_loc" to be what he wants and if he does not, (understand) it is taken from adif, if exist.
Should be user friendly way.

**Comment by phl0** [comment]
Roger. PR created: https://github.com/ok2cqr/cqrlog/pull/394 with a separate branch and a squash merge.
Issue will be closed on merge.

**Comment by phl0** [comment]
PR https://github.com/ok2cqr/cqrlog/pull/394 has been merged. So closing here.
